export const defaultGeometry = {
  upperIncisorX: 300,
  upperIncisorY: 200,
  lowerIncisorX: -25,
  lowerIncisorY: 0,
  bladeLength: 140,
  bladeThickness: 15,
  bladeInsertion: 72,
  bladeRadius: 118,
  bladeAngle: 18,
  tubeLength: 280,
  tubeRadius: 150,
  tubeOD: 10,
  tubeAngle: 26,
  glotticPlaneX: 165,
  fiducialStartAngle: 0,
  fiducialEndAngle: 360,
  fiducialThickness: 1,
  fiducialX: 0,
  fiducialY: 0,
};

export const presets = {
  normal: {
    tubeAngle: 26,
    tubeRadius: 150,
    tubeOD: 10,
    glotticPlaneX: 165,
    tubeLength: 280,
    bladeLength: 140,
    bladeThickness: 15,
    bladeInsertion: 72,
    bladeRadius: 118,
    bladeAngle: 18,
    lowerIncisorX: -25,
    lowerIncisorY: 0,
  },
  difficult: {
    tubeAngle: 35,
    tubeRadius: 150,
    tubeOD: 10,
    glotticPlaneX: 200,
    tubeLength: 280,
    bladeLength: 140,
    bladeThickness: 15,
    bladeInsertion: 65,
    bladeRadius: 118,
    bladeAngle: 25,
    lowerIncisorX: -15,
    lowerIncisorY: 10,
  },
  pediatric: {
    tubeAngle: 20,
    tubeRadius: 120,
    tubeOD: 6,
    glotticPlaneX: 130,
    tubeLength: 220,
    bladeLength: 100,
    bladeThickness: 10,
    bladeInsertion: 80,
    bladeRadius: 90,
    bladeAngle: 15,
    lowerIncisorX: -20,
    lowerIncisorY: 0,
  },
  optimal: {
    tubeAngle: 15,
    tubeRadius: 150,
    tubeOD: 10,
    glotticPlaneX: 165,
    tubeLength: 280,
    bladeLength: 140,
    bladeThickness: 15,
    bladeInsertion: 85,
    bladeRadius: 118,
    bladeAngle: 10,
    lowerIncisorX: -40,
    lowerIncisorY: -5,
  },
};
